import fs                     from 'fs';
import path                   from 'path';
import { fileURLToPath }      from 'url';

const ENVIRONMENT = process.env.NODE_ENV || "development";
const IS_PRODUCTION  = true &&(ENVIRONMENT === "production");
const IS_DEVELOPMENT = (ENVIRONMENT === "development");

// "chromium" or "firefox"
const PLATFORM = process.env.MX_PLATFORM

//
// PLATFORM_ID
//   - on Firefox, platform id is extension's id (generated by AMO).
//   - on Chromium, the extension's public key which will be hashed to extension id.
//
// We are not use the public key that generated by Chrome Web Store anymore,
// because it's dangerous, Chrome can use it to
// disable the installed extension without a reason.
//
const PLATFORM_ID = process.env.MX_PLATFORM_ID

// The update manifest file's URL that we self hosted (Chromium).
const PLATFORM_UPDATE_URL = process.env.MX_PLATFORM_UPDATE_URL


function checkEnvironmentVariables() {
  const errors = [];
  if (!PLATFORM)    { errors.push("PLATFORM is empty"); }
  if (!PLATFORM_ID) { errors.push("PLATFORM_ID is empty"); }

  if (IS_PRODUCTION && PLATFORM == 'chromium' && !PLATFORM_UPDATE_URL) {
    errors.push("PLATFORM_UPDATE_URL is empty")
  }
  if (errors.length > 0) {
    throw new Error(errors.join(", "))
  }
}

// Fix CJS global variables
const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const npm_folder = path.join(__dirname, "node_modules");
const ext_folder = path.join(__dirname, "dist", "extension");
const  mx_folder = path.join(ext_folder, "maoxian-web-clipper");

const manifestPath_common   = path.join(__dirname, "src", "manifest.json")
const manifestPath_Firefox  = path.join(__dirname, "src", "manifest-firefox.json")
const manifestPath_Chromium = path.join(__dirname, "src", "manifest-chromium.json")


// extension page names
const pages = [
  'popup',
  'welcome',
  'history',
  'home',
  'last-clipping-result',
  'plan-subscription',
  'reset-history',
  'setting',
  'ui-control',
  'ui-selection',
  'failed-tasks',
  'user-script',
  'sync-user-scripts',
  'debug',
  'off-screen'
];

function getCopyItems() {

  const items = [];

  // 3rd party js and css
  [
    ['src/vendor', 'vendor']
  ].forEach((pair) => {
    const sourceFilename = path.join(__dirname, pair[0]);
    const targetFilename = path.join(mx_folder, pair[1]);
    items.push({from: sourceFilename, to: targetFilename});
  });

  [
    [
      'css.escape/css.escape.js',
      'vendor/js/css.escape.js'
    ], [
      'awesomplete/awesomplete.js',
      'vendor/js/awesomplete.js'
    ], [
      'awesomplete/awesomplete.css',
      'vendor/css/awesomplete.css'
    ], [
      'pikaday/pikaday.js',
      'vendor/js/pikaday.js'
    ], [
      'turndown/lib/turndown.browser.es.js',
      'vendor/js/turndown.js'
    ], [
      'turndown-plugin-gfm/lib/turndown-plugin-gfm.browser.es.js',
      'vendor/js/turndown-plugin-gfm.js'
    ], [
      'mustache/mustache.mjs',
      'vendor/js/mustache.js'
    ], [
      'mathml2latex/lib/mathml2latex.browser.es.js',
      'vendor/js/mathml2latex.js'
    ], [
      'pikaday/css/pikaday.css',
      'vendor/css/pikaday.css'
    ],
  ].forEach((pair) => {
    const sourceFilename = path.join(npm_folder, pair[0]);
    const targetFilename = path.join( mx_folder, pair[1]);
    items.push({from: sourceFilename, to: targetFilename});
  });

  // page assets
  [
    /* jsons, icons and locale files */
    //['src/json', 'json'],
    ['src/icons', 'icons'],
    ['src/_locales/en',    '_locales/en' ],
    ['src/_locales/zh_CN', '_locales/zh_CN' ],
    ['src/_locales/pikaday.i18n.js', '_locales/pikaday.i18n.js' ],

    /* js */
    ['src/js', 'js'],
    /* platform relative js */
    [`src/js/lib/frame-tool-${PLATFORM}.js`, 'js/lib/frame-tool.js'],

  ].forEach((pair) => {
    const sourceFilename = path.join(__dirname, pair[0]);
    const targetFilename = path.join(mx_folder, pair[1]);
    items.push({from: sourceFilename, to: targetFilename});
  })

  // page htmls
  pages.forEach((name) => {
    const sourceFilename = path.join(__dirname, `src/pages/${name}.html`);
    const targetFilename = path.join(mx_folder, `pages/${name}.html`);
    items.push({from: sourceFilename, to: targetFilename});
  });

  // page javascripts
  ['reset-history-worker'].concat(pages).forEach((name) => {
    const sourceFilename = path.join(__dirname, `src/pages/${name}.js`);
    const targetFilename = path.join(mx_folder, `pages/${name}.js`);
    items.push({from: sourceFilename, to: targetFilename});
  });


  // page stylesheets
  const cssBlackList = ['ui-selection',
    'reset-history', 'plan-subscription', 'user-script', 'sync-user-scripts', 'off-screen'];
  const cssNames = ['_base', '_details', '_file-uploader'].concat(pages);
  cssNames.forEach((name) => {
    if (cssBlackList.indexOf(name) == -1) {
      items.push({
        from: path.join(__dirname, `src/pages/${name}.css`),
        to  : path.join(mx_folder, `pages/${name}.css`),
      });
    }
  });

  // manifest
  items.push({
    from: path.join(__dirname, 'src/manifest.json'),
    to  : path.join(mx_folder, 'manifest.json'),
    transform: renderManifestWithPlatformMsg,
  });

  // env
  let envJs;
  if (IS_PRODUCTION) {
    envJs = 'src/js/env.production.js';
  } else {
    envJs = 'src/js/env.js';
  }

  items.push({
    from: path.join(__dirname, envJs),
    to  : path.join(mx_folder, 'js/env.js'),
  });

  return items;
}

function getRemoveItems() {
  return [
    'js/env.production.js',
    'js/lib/frame-tool-firefox.js',
    'js/lib/frame-tool-chromium.js',
  ].map((it) => path.join(mx_folder, it));
}


function renderManifestWithPlatformMsg(content, path) {
  const common = JSON.parse(content.toString());

  let diff;
  switch(PLATFORM) {
    case 'chromium':
      diff = JSON.parse(fs.readFileSync(manifestPath_Chromium));
      if (PLATFORM_ID) {
        diff.key = PLATFORM_ID;
      } else {
        delete diff.key;
      }
      if (PLATFORM_UPDATE_URL) {
        diff.update_url = PLATFORM_UPDATE_URL;
      } else {
        delete diff.update_url;
      }
      break;
    case 'firefox':
      diff = JSON.parse(fs.readFileSync(manifestPath_Firefox));
      if (PLATFORM_ID) {
        diff.browser_specific_settings.gecko.id = PLATFORM_ID;
      }
      break;
    default: break;
  }

  const manifest = Object.assign({}, common, diff);
  return Buffer.from(JSON.stringify(manifest, null, 2));
}

function cleanTargetDirectory() {
  // Clean dist/extension/maoxian-web-clipper before every build.
  if (fs.existsSync(mx_folder)) {
    fs.rmSync(mx_folder, {force: true, recursive: true});
  }

  fs.mkdirSync(mx_folder, {recursive: true});
  console.info("mx_folder ready!");
}


function copySourceFiles() {
  console.debug("copy source files to maoxian folder");
  const add_items = getCopyItems();
  add_items.forEach((it) => {
    if (!fs.existsSync(it.from)) {
      console.error(it);
      throw new Error("File not exist: ", it.from);
    }
    if (it.transform && typeof(it.transform) == "function") {
      const content = fs.readFileSync(it.from);
      const modifiedContent = it.transform(content);
      fs.writeFileSync(it.to, modifiedContent, {mode: 0o660});
    } else {
      fs.cpSync(it.from, it.to, {recursive: true, force: true});
    }
  });

  console.debug("remove environment specific files");
  const rm_items = getRemoveItems();
  rm_items.forEach((it) => {
    if (fs.existsSync(it)) {
      fs.rmSync(it, {force: true});
    }
  });
}

function mkdirIfNotExist(dir) {
  try {
    fs.mkdirSync(dir, {recursive: true});
  } catch(e) {
    console.info("mkdir if not exist: ", e.message, dir);
  }
}

function compressAsZip() {
  // Compress dist/extension/maoxian-web-clipper
  const manifest = JSON.parse(fs.readFileSync(manifestPath_common));
  const zip_file = `maoxian-web-clipper-${PLATFORM}-${manifest.version}.zip`
  const zip_path = path.join(ext_folder, zip_file);
  // FIXME
  // if zip_path exist, remove it
  //if (fs.existsSync(zip_path)) {
  //  fs.rmSync(zip_path, {force: true});
  //}
  console.debug("compressAsZip!", zip_file);
}

function build() {
  cleanTargetDirectory();
  copySourceFiles();

  if (IS_PRODUCTION) {
    compressAsZip();
  }
}

function main() {
  checkEnvironmentVariables();
  build();
}

main();
